package dev.kof.compiler.js;

/** kof-runtime-io.mjs — plataforma (fs/console). */
public final class JsRuntimeIo {
    private JsRuntimeIo() {
    }

    static  String IO_RUNTIME = """
            // KofJS platform runtime — filesystem/console operations for the
            // KofJS target. Generated by the Kof compiler (KofJS backend).
            //
            // This module delegates to the kof_platform object exposed by the
            // Kof process (dev.kof.runtime.KofJsRunner) when Kof executes the
            // generated module with its embedded JavaScript engine. The
            // generated .mjs files are standard ES2022+ modules and do not
            // depend on Node.js or any other external runtime.
            //
            // In a browser (kof-webview / web deployment) there is no
            // kof_platform host object: console operations fall back to the
            // browser console and IO operations report a clear error instead
            // of a ReferenceError.

            const kof_platform = globalThis.kof_platform || new Proxy({ print(x) { console.log(String(x)); } }, {
                get(t, prop) {
                    if (prop in t) return t[prop];
                    return function () {
                        throw new Error("kof.io: " + String(prop) + " is not available in the browser");
                    };
                }
            });

            export function kofPrint(x) {
                kof_platform.print(String(x));
            }

            // R3 fatia 3.6 (JS FFI parity): extern lowers to kofFfi/kofFfiVoid,
            // which delegate to the host runner's kof_platform.ffi (KofJsFfiBridge,
            // java.lang.foreign on the GraalJS/node host). No kof_platform host in a
            // browser -> the kof_platform Proxy throws an honest runtime error, the
            // same degrade as kof.io/console (R7), never a silent stub.
            export function kofFfi(lib, name, sig, args) {
                return kof_platform.ffi(lib, name, sig, args);
            }

            export function kofFfiVoid(lib, name, sig, args) {
                kof_platform.ffi_void(lib, name, sig, args);
            }

            export function kofArgs() {
                if (kof_platform.args) {
                    return kof_platform.args();
                }
                if (typeof process !== "undefined" && process.argv) {
                    return process.argv.slice(2);
                }
                return [];
            }

            export function kofProcessRun(program, args) {
                return kofResult(kof_platform.processRun(program, args));
            }

            // §367: todo Result de process/shell e impresso por CONTEUDO
            // ("ProcessResult[exitCode=0, stdout=x, stderr=]"). No host Graal o
            // Map ja chega como KofJsProcessBridge$KofResult (toString do host,
            // espelha o ProcessResult JVM); browser/objeto cru: printer local
            // identico. Acesso a stdout/stderr/exitCode NAO muda (additive).
            function kofResult(result) {
                if (!result) return result;
                if (String(result.constructor && result.constructor.name || "")
                        .indexOf("KofResult") >= 0) {
                    return result;
                }
                const trimEnd = (s) => String(s == null ? "" : s).replace(/\s+$/, "");
                result.toString = function () {
                    return "ProcessResult[exitCode=" + result.exitCode
                            + ", stdout=" + trimEnd(result.stdout)
                            + ", stderr=" + trimEnd(result.stderr) + "]";
                };
                return result;
            }

            // kof.shell (Stage 2 / 2.2): argv builder — [program] + args, sempre
            // lista, nunca string concatenada (classe de segurança do sh -c).
            export function kofShellArgv(program, args) {
                return [program, ...args];
            }

            // kof.ssh (Stage 2 / 2.3): argv builder — host e command ficam UM
            // elemento cada (mesma classe de segurança do sh -c). BatchMode +
            // ConnectTimeout: nao-interativo e limitado no tempo.
            export function kofSshArgv(host, command) {
                return ["ssh", "-o", "BatchMode=yes", "-o", "ConnectTimeout=5", host, command];
            }

            // kof.ssh run(host, command) — delega ao MESMO processRun do host
            // (KofJsProcessBridge/JVM), logo paridade por construcao. Sem host
            // (browser) o Proxy honesto acima degrada com erro alto (R7).
            export function kofSshRun(host, command) {
                return kofResult(kof_platform.processRun("ssh",
                        ["-o", "BatchMode=yes", "-o", "ConnectTimeout=5", host, command]));
            }

            // kof.shell runWith(argv, cwd, env) — 2.2.3. Map do Kof é JS Map
            // nativo; o host recebe objeto plain de strings. Browser sem
            // kof_platform: o Proxy honesto acima degrada (R7), nunca stub.
            export function kofShellRunWith(argv, cwd, env) {
                const o = {};
                if (env) {
                    env.forEach((v, k) => { o[String(k)] = String(v); });
                }
                return kofResult(kof_platform.processRunWith(argv, cwd || "", o));
            }

            // kof.process spawn (F10) — pipes vivos no host JS (KofJsProcessBridge).
            // Convenção espelha o binding JVM byte-a-byte: handle = número, spawn
            // falho = -1, readLine EOF/morto = "", exitCode vivo = MIN_VALUE,
            // alive = 1/0. Browser sem kof_platform: o Proxy honesto acima degrada
            // com erro alto (R7), nunca stub.
            export function kofProcessSpawn(program, args) {
                return kof_platform.processSpawn(program, args);
            }
            export function kofSpawnWrite(h, data) {
                kof_platform.spawnWrite(h, data);
            }
            export function kofSpawnReadLine(h) {
                return kof_platform.spawnReadLine(h);
            }
            export function kofSpawnExitCode(h) {
                return kof_platform.spawnExitCode(h);
            }
            export function kofSpawnKill(h) {
                kof_platform.spawnKill(h);
            }
            export function kofSpawnAlive(h) {
                return kof_platform.spawnAlive(h) === 1;
            }

            // kof.shell pipeline(stages) — cadeia stdout→stdin real no host
            // (KofJsProcessBridge: mesma cadeia + pump threads do binding JVM).
            export function kofShellPipeline(stages) {
                return kofResult(kof_platform.processPipeline(stages));
            }

            // §239 (JS): String.format delega ao host (java.lang.String.format ->
            // paridade byte-a-byte). Sem kof_platform (browser) o Proxy acima da
            // tabela lança erro honesto — nunca um resultado errado em silêncio (R6/R7).
            export function kofStringFormat(fmt, argsArr) {
                return kof_platform.stringFormat(fmt, argsArr);
            }

            export function kofProcessExit(code) {
                // sentinel: o runner converte no exit code do processo
                throw { __kof_exit__: code };
            }

            export function kofReadLine() {
                return kof_platform.readLine();
            }

            export function kofReadFile(p) {
                return kof_platform.readFile(p);
            }

            export function kofWriteFile(p, content) {
                return kof_platform.writeFile(p, content);
            }

            export function kofIoFileExists(p) {
                return kof_platform.fileExists(p);
            }

            export function kofIoFileIsFile(p) {
                return kof_platform.fileIsFile(p);
            }

            export function kofIoFileIsDir(p) {
                return kof_platform.fileIsDir(p);
            }

            export function kofIoReadText(p) {
                return kof_platform.readText(p);
            }

            export function kofIoWriteText(p, content) {
                return kof_platform.writeText(p, content);
            }

            export function kofIoAppendText(p, content) {
                return kof_platform.appendText(p, content);
            }

            export function kofIoReadBytes(p) {
                return kof_platform.readBytes(p);
            }

            export function kofIoWriteBytes(p, bytes) {
                return kof_platform.writeBytes(p, bytes);
            }

            export function kofIoAppendBytes(p, bytes) {
                return kof_platform.appendBytes(p, bytes);
            }

            export function kofIoDelete(p) {
                return kof_platform.delete(p);
            }

            export function kofIoFileSize(p) {
                return kof_platform.fileSize(p);
            }

            export function kofIoFileName(p) {
                return kof_platform.fileName(p);
            }

            export function kofIoPathParent(p) {
                return kof_platform.pathParent(p);
            }

            export function kofIoPathFileName(p) {
                return kof_platform.pathFileName(p);
            }

            export function kofIoPathExtension(p) {
                return kof_platform.pathExtension(p);
            }

            export function kofIoPathNormalize(p) {
                return kof_platform.pathNormalize(p);
            }

            export function kofIoPathResolve(base, child) {
                return kof_platform.pathResolve(base, child);
            }

            export function kofIoPathIsAbsolute(p) {
                return kof_platform.pathIsAbsolute(p);
            }

            export function kofIoPathToAbsolute(p) {
                return kof_platform.pathToAbsolute(p);
            }

            export function kofIoDirCreate(p) {
                return kof_platform.dirCreate(p);
            }

            export function kofIoDirCreateDirs(p) {
                return kof_platform.dirCreateDirs(p);
            }

            export function kofIoDirDelete(p) {
                return kof_platform.dirDelete(p);
            }

            export function kofIoDirList(p) {
                return kof_platform.dirList(p);
            }

            // ── kof.db (DB001) — delegacao ao host (mesmo classpath JDBC do
            // caminho JVM; sem host = shim #104 com erro claro). Rows voltam
            // como List<String> json (contrato List<STR> do frontend).
            export function kofDbConnect(url) {
                return kof_platform.dbConnect(url);
            }

            export function kofDbConnect2(url, user, pass) {
                return kof_platform.dbConnect2(url, user, pass);
            }

            export function kofDbClose(id) {
                return kof_platform.dbClose(id);
            }

            export function kofDbExecute(id, sql) {
                return kof_platform.dbExecute(id, sql, []);
            }

            export function kofDbExecute1(id, sql, a) {
                return kof_platform.dbExecute(id, sql, [a]);
            }

            export function kofDbExecute2(id, sql, a, b) {
                return kof_platform.dbExecute(id, sql, [a, b]);
            }

            export function kofDbExecute3(id, sql, a, b, c) {
                return kof_platform.dbExecute(id, sql, [a, b, c]);
            }

            export function kofDbExecute4(id, sql, a, b, c, d) {
                return kof_platform.dbExecute(id, sql, [a, b, c, d]);
            }

            export function kofDbQuery0(id, sql, cls) {
                return kof_platform.dbQuery(id, sql, cls == null ? "" : String(cls), []);
            }

            export function kofDbQuery1(id, sql, a, cls) {
                return kof_platform.dbQuery(id, sql, cls == null ? "" : String(cls), [a]);
            }

            export function kofDbQuery2(id, sql, a, b, cls) {
                return kof_platform.dbQuery(id, sql, cls == null ? "" : String(cls), [a, b]);
            }

            export function kofDbQuery3(id, sql, a, b, c, cls) {
                return kof_platform.dbQuery(id, sql, cls == null ? "" : String(cls), [a, b, c]);
            }

            export function kofDbQuery4(id, sql, a, b, c, d, cls) {
                return kof_platform.dbQuery(id, sql, cls == null ? "" : String(cls), [a, b, c, d]);
            }

            export function kofDbTransaction(fn) {
                return kof_platform.dbTransaction(fn);
            }

            // ORM001 (18/09) — kof.orm no JS sobre a mesma conn do kof.db
            // (KofJsOrmBridge). O registro e serializado pelo toJSON()
            // sintetico do record (chaves limpas id/name/...); o bind tipado da
            // volta acontece no guest (JsRuntimeOps __kof_decode_<T>), com
            // paridade byte-a-byte com JvmOrmRuntime. O className do wire e
            // ignorado: a ponte le o schema, nao a classe.
            export function kofOrmSingle(r, dec) { return r == null ? null : dec(r); }

            export function kofOrmCreate(id, table, schema) {
                return kof_platform.ormCreate(id, table, schema);
            }

            export function kofOrmSave(id, obj, table, schema) {
                return kof_platform.ormSave(id, obj.toJSON(), table, schema);
            }

            export function kofOrmSaveAll(id, items, table, schema) {
                return kof_platform.ormSaveAll(id, items.map(o => o.toJSON()), table, schema);
            }

            export function kofOrmFind(id, key, table, schema, cls) {
                return kof_platform.ormFind(id, key, table, schema);
            }

            export function kofOrmAll(id, table, schema, cls) {
                return kof_platform.ormAll(id, table, schema);
            }

            export function kofOrmWhere(id, field, value, table, schema, cls) {
                return kof_platform.ormWhere(id, field, value, table, schema);
            }

            export function kofOrmWhereOp(id, field, op, value, table, schema, cls) {
                return kof_platform.ormWhereOp(id, field, op, value, table, schema);
            }

            export function kofOrmCount(id, table, schema) {
                return kof_platform.ormCount(id, table, schema);
            }

            export function kofOrmCountWhere(id, field, value, table, schema) {
                return kof_platform.ormCountWhere(id, field, value, table, schema);
            }

            export function kofOrmDelete(id, key, table, schema) {
                return kof_platform.ormDelete(id, key, table, schema);
            }

            export function kofOrmDeleteAll(id, table, schema) {
                return kof_platform.ormDeleteAll(id, table, schema);
            }

            export function kofOrmPage(id, limit, offset, table, schema, cls) {
                return kof_platform.ormPage(id, limit, offset, table, schema);
            }

            export function kofOrmMigrate(id, name, sql) {
                return kof_platform.ormMigrate(id, name, sql);
            }
            """;

}
